name: "Execute E2E Tests nightly"
env:
  DEPLOY_URL: https://dashboard.nexudus.com/dashboards/now
  APP_ENVIRONMENT: Stage
  ECR_REPO_NAME: fo-frontend

on:
  schedule:
    - cron:  '0 7 * * MON-FRI'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout UI"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v2.1.3
        with:
          node-version: 14.x
      - name: "Run e2e"
        id: e2e_tests
        env:
          LAUNCH_REPORT: false
          BASE_URL: ${{ env.DEPLOY_URL }}
          MOCK_API: false
        run: |
          npm install
          npm test
      - name: Notify team
        if: ${{ always() }}
        uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
        with:
          webhook_url: ${{ secrets.WEBHOOK_DEPLOYMENT_STAGING }}
          title: 'E2E tests nightly execution on staging -- Outcome --> ${{ steps.e2e_tests.outcome }}'
          text: 'Please follow the link to see the results: <link>https://e2e.results.stage.facultyopinions.com/${{ steps.upload_report.outputs.reportName }}</link>'